tagFormat: ${version}

plugins:
  - @semantic-release/commit-analyzer
  - @semantic-release/release-notes-generator
  - - @semantic-release/changelog
    - changelogFile: docs/CHANGELOG.md
  - - @semantic-release/git
    - message: "release: 🚀 ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      assets: [docs/CHANGELOG.md]
  - - @semantic-release/github
    - assets:
        - path: build/libs/*.jar
          label: Slugger Jars
  - - @semantic-release/exec
    - prepareCmd: './gradlew clean assemble'
